receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4417"
      http:
        endpoint: "0.0.0.0:4418"

exporters:
  debug:
  otlp:
    endpoint: "http://tempo:4417"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp, debug ]
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus, debug ]



